from datetime import datetime


class SimpleReportGenerator:
    """Generate simple, consumer-friendly reports"""
    
    def generate_report(self, data, anomaly_results=None):
        """Generate plain English report"""
        
        lines = []
        lines.append("=" * 60)
        lines.append("📊 NETWORK HEALTH REPORT")
        lines.append("=" * 60)
        lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        lines.append("")
        
        # Basic stats
        lines.append("📁 DATA OVERVIEW")
        lines.append("-" * 40)
        lines.append(f"Records analyzed: {len(data):,}")
        lines.append(f"Features: {len(data.columns)}")
        lines.append("")
        
        # Health status
        if anomaly_results is not None:
            issue_count = anomaly_results['anomaly'].sum()
            issue_rate = issue_count / len(data) * 100
            health_score = 100 - issue_rate
            
            lines.append("🏥 HEALTH STATUS")
            lines.append("-" * 40)
            
            if health_score >= 80:
                lines.append("✅ Status: HEALTHY")
                lines.append("Your network is operating normally.")
            elif health_score >= 50:
                lines.append("⚠️ Status: NEEDS ATTENTION")
                lines.append("Some unusual activity detected.")
            else:
                lines.append("🔴 Status: CRITICAL")
                lines.append("Immediate review recommended.")
            
            lines.append("")
            lines.append(f"Health Score: {health_score:.0f}%")
            lines.append(f"Issues Found: {issue_count:,}")
            lines.append(f"Issue Rate: {issue_rate:.1f}%")
            lines.append("")
        
        # Key metrics
        lines.append("📈 KEY METRICS")
        lines.append("-" * 40)
        
        numeric_cols = data.select_dtypes(include=['number']).columns
        for col in list(numeric_cols)[:3]:
            lines.append(f"{col}:")
            lines.append(f"  Average: {data[col].mean():.2f}")
            lines.append(f"  Range: {data[col].min():.2f} - {data[col].max():.2f}")
            lines.append("")
        
        # Recommendations
        if anomaly_results is not None:
            lines.append("💡 RECOMMENDATIONS")
            lines.append("-" * 40)
            
            if health_score >= 80:
                lines.append("• Continue regular monitoring")
                lines.append("• Review settings quarterly")
            elif health_score >= 50:
                lines.append("• Review detected issues")
                lines.append("• Check for unusual patterns")
                lines.append("• Update security settings")
            else:
                lines.append("• IMMEDIATE: Review critical issues")
                lines.append("• Check for security breaches")
                lines.append("• Update all security measures")
                lines.append("• Consult IT security team")
        
        lines.append("")
        lines.append("=" * 60)
        lines.append("Report generated by Network Health Monitor")
        
        return "\n".join(lines)